/**
 * AnyMind API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface CurrencyUnit {
    code: string;
    numericCode: number;
    decimalPlaces: number;
    symbol: string;
    defaultFractionDigits: number;
    currencyCode: string;
    numeric3Code: string;
    countryCodes: Array<string>;
    pseudoCurrency: boolean;
}
