/**
 * AnyMind API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.32
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GetAnswer } from './getAnswer';
import { GetReport } from './getReport';


export interface GetCommentDetails {
    commentId: string;
    content: string;
    answer?: GetAnswer;
    report?: GetReport;
    createdAt: Date;
}
