/**
 * AnyMind API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ServiceUsageDetails } from './serviceUsageDetails';
import { SimpleClientFinancialOperation } from './simpleClientFinancialOperation';


export interface GetClientActivity {
    accountId: string;
    activityType: GetClientActivity.ActivityTypeEnum;
    serviceId?: string;
    expertId?: string;
    serviceName?: string;
    serviceOwnerId?: string;
    serviceUsageDetails?: ServiceUsageDetails;
    financialOperation?: SimpleClientFinancialOperation;
    initializedAt: Date;
}
export namespace GetClientActivity {
    export type ActivityTypeEnum = 'SERVICE_USAGE_EVENT' | 'FINANCIAL_TRANSACTION';
    export const ActivityTypeEnum = {
        SERVICEUSAGEEVENT: 'SERVICE_USAGE_EVENT' as ActivityTypeEnum,
        FINANCIALTRANSACTION: 'FINANCIAL_TRANSACTION' as ActivityTypeEnum
    }
}
