/**
 * AnyMind API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GetClientDetails } from './getClientDetails';
import { MoneyDto } from './moneyDto';


export interface GetExpertCallSummary {
    serviceUsageEventId: string;
    clientDetails: GetClientDetails;
    callProfit: MoneyDto;
    serviceName: string;
    callDuration: number;
}
