/**
 * AnyMind API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GetOrganizationDetails } from './getOrganizationDetails';
import { GetService } from './getService';


export interface GetEmploymentDetails {
    id: string;
    service: GetService;
    organizationDetails?: GetOrganizationDetails;
    employeeId: string;
    usageCounter: number;
    commentCounter: number;
    rating?: number;
    createdAt: Date;
}
