/**
 * AnyMind API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GetProfileDetails } from './getProfileDetails';
import { GetService } from './getService';
import { GetTag } from './getTag';


export interface GetOrganizationServiceDetails {
    service: GetService;
    employees: Array<GetProfileDetails>;
    tags: Array<GetTag>;
}
