/**
 * AnyMind API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GetExpertDetails } from './getExpertDetails';
import { GetOrganizationDetails } from './getOrganizationDetails';


export interface GetProfileWithDocuments {
    id: string;
    isActive: boolean;
    organizationDetails?: GetOrganizationDetails;
    expertDetails?: GetExpertDetails;
}
