/**
 * AnyMind API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MoneyDto } from './moneyDto';


export interface GetPromoCode {
    id: string;
    token: string;
    amount: MoneyDto;
    issuer: string;
    status: GetPromoCode.StatusEnum;
    expiresAt: Date;
    createdAt: Date;
    updatedAt?: Date;
}
export namespace GetPromoCode {
    export type StatusEnum = 'NEW' | 'REDEEMED';
    export const StatusEnum = {
        NEW: 'NEW' as StatusEnum,
        REDEEMED: 'REDEEMED' as StatusEnum
    }
}
