/**
 * AnyMind API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.53
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GetPayoutMethod } from './getPayoutMethod';
import { MoneyDto } from './moneyDto';
import { ServiceUsageDetails } from './serviceUsageDetails';


export interface GetProfileActivity {
    id: string;
    accountId: string;
    payoutId?: string;
    activityType: GetProfileActivity.ActivityTypeEnum;
    serviceId?: string;
    expertId?: string;
    serviceName?: string;
    serviceOwnerId?: string;
    isFreelanceService?: boolean;
    serviceUsageDetails?: ServiceUsageDetails;
    amount?: MoneyDto;
    payoutMethod?: GetPayoutMethod;
    payoutType?: GetProfileActivity.PayoutTypeEnum;
    invoiceId?: string;
    initializedAt: Date;
}
export namespace GetProfileActivity {
    export type ActivityTypeEnum = 'SERVICE_USAGE_EVENT' | 'PAYOUT' | 'REFUND';
    export const ActivityTypeEnum = {
        SERVICEUSAGEEVENT: 'SERVICE_USAGE_EVENT' as ActivityTypeEnum,
        PAYOUT: 'PAYOUT' as ActivityTypeEnum,
        REFUND: 'REFUND' as ActivityTypeEnum
    }
    export type PayoutTypeEnum = 'PROFILE' | 'PARTNER';
    export const PayoutTypeEnum = {
        PROFILE: 'PROFILE' as PayoutTypeEnum,
        PARTNER: 'PARTNER' as PayoutTypeEnum
    }
}
