/**
 * AnyMind API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.32
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface PaymentSystem {
    id?: string;
    name: PaymentSystem.NameEnum;
}
export namespace PaymentSystem {
    export type NameEnum = 'PayPal' | 'PayU' | 'CreditCard';
    export const NameEnum = {
        PayPal: 'PayPal' as NameEnum,
        PayU: 'PayU' as NameEnum,
        CreditCard: 'CreditCard' as NameEnum
    }
}
