/**
 * AnyMind API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.20
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface PaymentLink {
    value: string;
    name: string;
    brandImageUrl: string;
    status: PaymentLink.StatusEnum;
}
export namespace PaymentLink {
    export type StatusEnum = 'ENABLED' | 'DISABLED' | 'TEMPORARY_DISABLED';
    export const StatusEnum = {
        ENABLED: 'ENABLED' as StatusEnum,
        DISABLED: 'DISABLED' as StatusEnum,
        TEMPORARYDISABLED: 'TEMPORARY_DISABLED' as StatusEnum
    }
}
