/**
 * AnyMind API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.20
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface PostAddNewCard {
    name: string;
    email: string;
    encryptedCard: string;
    expiryDate: string;
    cardType: PostAddNewCard.CardTypeEnum;
    language?: PostAddNewCard.LanguageEnum;
    redirectUrlOnSuccess?: string;
    redirectUrlOnFailure?: string;
}
export namespace PostAddNewCard {
    export type CardTypeEnum = 'AMEX' | 'DINERS' | 'MASTERCARD' | 'VISA' | 'OTHER';
    export const CardTypeEnum = {
        AMEX: 'AMEX' as CardTypeEnum,
        DINERS: 'DINERS' as CardTypeEnum,
        MASTERCARD: 'MASTERCARD' as CardTypeEnum,
        VISA: 'VISA' as CardTypeEnum,
        OTHER: 'OTHER' as CardTypeEnum
    }
    export type LanguageEnum = 'pl' | 'en';
    export const LanguageEnum = {
        Pl: 'pl' as LanguageEnum,
        En: 'en' as LanguageEnum
    }
}
