/**
 * AnyMind API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.30
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface PostCommentReport {
    cause: PostCommentReport.CauseEnum;
}
export namespace PostCommentReport {
    export type CauseEnum = 'FALSE_COMMENT' | 'OFFENSIVE_COMMENT' | 'SPAM_COMMENT';
    export const CauseEnum = {
        FALSECOMMENT: 'FALSE_COMMENT' as CauseEnum,
        OFFENSIVECOMMENT: 'OFFENSIVE_COMMENT' as CauseEnum,
        SPAMCOMMENT: 'SPAM_COMMENT' as CauseEnum
    }
}
