/**
 * AnyMind API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GetProfile } from './getProfile';
import { MoneyDto } from './moneyDto';


export interface ServiceWithOwnerProfile {
    id: string;
    ownerProfile: GetProfile;
    name: string;
    description: string;
    price: MoneyDto;
    language: string;
    isSuspended: boolean;
    isFreelance: boolean;
    createdAt: Date;
    deletedAt?: Date;
}
