/**
 * AnyMind API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.20
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PostPayment } from './postPayment';


export interface VerifyPayment {
    paymentId: string;
    state: string;
    amount: string;
    currency: string;
    responseType: string;
    postPayment: PostPayment;
}
