stages:
  - prepare-container
  - build
  - push-npm
  - cleanup_build

variables:
  # Update from $CI_COMMIT_SHA to $CI_PIPELINE_IID when gitlab > v.11
  CONTAINER_TEST_NAME: anymind-ng-api:test-$CI_COMMIT_SHA

test-prepare-job:
  stage: prepare-container
  script:
    - docker build --no-cache -t $CONTAINER_TEST_NAME -f Dockerfile.test .
  tags:
    - shell

test-run-job:
  stage: build
  script:
    - docker run -i $CONTAINER_TEST_NAME /bin/sh -c 'npm install && npm run build'
  tags:
    - shell

push-npm-job:
  stage: push-npm
  only:
    - develop
  script:
    - docker run -i $CONTAINER_TEST_NAME /bin/sh -c 'npm run publish'
  tags:
    - shell

cleanup_build-job:
  stage: cleanup_build
  script:
    - docker rmi -f $CONTAINER_TEST_NAME
  tags:
    - shell
