/**
 * AnyMind API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { Account } from '../model/account';
import { ChangeAccountPassword } from '../model/changeAccountPassword';
import { ChangeAccountPasswordMobile } from '../model/changeAccountPasswordMobile';
import { ConfirmMsisdnVerificationRequest } from '../model/confirmMsisdnVerificationRequest';
import { Country } from '../model/country';
import { CreateMsisdnVerificationRequest } from '../model/createMsisdnVerificationRequest';
import { GetCallInvoiceDetails } from '../model/getCallInvoiceDetails';
import { GetCompanyInvoiceDetails } from '../model/getCompanyInvoiceDetails';
import { GetMobileProtectedViews } from '../model/getMobileProtectedViews';
import { GetPersonalInvoiceDetails } from '../model/getPersonalInvoiceDetails';
import { GetSessionWithAccount } from '../model/getSessionWithAccount';
import { PatchAccount } from '../model/patchAccount';
import { PatchMobileViewsPermissions } from '../model/patchMobileViewsPermissions';
import { PostCallInvoiceDetails } from '../model/postCallInvoiceDetails';
import { PostCompanyInvoiceDetails } from '../model/postCompanyInvoiceDetails';
import { PostMobileViewsPermissions } from '../model/postMobileViewsPermissions';
import { PostPersonalInvoiceDetails } from '../model/postPersonalInvoiceDetails';
import { PutAccount } from '../model/putAccount';
import { PutGeneralSettings } from '../model/putGeneralSettings';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class AccountService {

    protected basePath = 'https://localhost';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (let consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Change account password
     * 
     * @param body Change account object
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public changePasswordMobileRoute(body: ChangeAccountPasswordMobile, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public changePasswordMobileRoute(body: ChangeAccountPasswordMobile, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public changePasswordMobileRoute(body: ChangeAccountPasswordMobile, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public changePasswordMobileRoute(body: ChangeAccountPasswordMobile, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling changePasswordMobileRoute.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<any>(`${this.basePath}/api/accounts/settings/mobile/change-password`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Change account password
     * 
     * @param body Change account object
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public changePasswordRoute(body: ChangeAccountPassword, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public changePasswordRoute(body: ChangeAccountPassword, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public changePasswordRoute(body: ChangeAccountPassword, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public changePasswordRoute(body: ChangeAccountPassword, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling changePasswordRoute.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.put<any>(`${this.basePath}/api/accounts/settings/change-password`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Confirm msisdn verification
     * 
     * @param body Verification token
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public confirmMsisdnVerificationRoute(body: ConfirmMsisdnVerificationRequest, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public confirmMsisdnVerificationRoute(body: ConfirmMsisdnVerificationRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public confirmMsisdnVerificationRoute(body: ConfirmMsisdnVerificationRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public confirmMsisdnVerificationRoute(body: ConfirmMsisdnVerificationRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling confirmMsisdnVerificationRoute.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<any>(`${this.basePath}/api/accounts/settings/msisdn-verification/confirm`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Check if email is taken
     * 
     * @param email Email
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAccountEmailExistsRoute(email: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public getAccountEmailExistsRoute(email: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public getAccountEmailExistsRoute(email: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public getAccountEmailExistsRoute(email: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (email === null || email === undefined) {
            throw new Error('Required parameter email was null or undefined when calling getAccountEmailExistsRoute.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<any>(`${this.basePath}/api/accounts/exists/email/${encodeURIComponent(String(email))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get call invoice details
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getCallInvoiceDetailsRoute(observe?: 'body', reportProgress?: boolean): Observable<GetCallInvoiceDetails>;
    public getCallInvoiceDetailsRoute(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<GetCallInvoiceDetails>>;
    public getCallInvoiceDetailsRoute(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<GetCallInvoiceDetails>>;
    public getCallInvoiceDetailsRoute(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<GetCallInvoiceDetails>(`${this.basePath}/api/accounts/settings/invoice-details/call`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get payout invoice details for company
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getCompanyPayoutInvoiceDetailsRoute(observe?: 'body', reportProgress?: boolean): Observable<GetCompanyInvoiceDetails>;
    public getCompanyPayoutInvoiceDetailsRoute(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<GetCompanyInvoiceDetails>>;
    public getCompanyPayoutInvoiceDetailsRoute(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<GetCompanyInvoiceDetails>>;
    public getCompanyPayoutInvoiceDetailsRoute(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<GetCompanyInvoiceDetails>(`${this.basePath}/api/accounts/settings/invoice-details/company`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get mobile protected views
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getMobileProtectedViewsRoute(observe?: 'body', reportProgress?: boolean): Observable<GetMobileProtectedViews>;
    public getMobileProtectedViewsRoute(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<GetMobileProtectedViews>>;
    public getMobileProtectedViewsRoute(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<GetMobileProtectedViews>>;
    public getMobileProtectedViewsRoute(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<GetMobileProtectedViews>(`${this.basePath}/api/accounts/mobile-permissions/protected-views`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get payout invoice details for person
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getPersonalPayoutInvoiceDetailsRoute(observe?: 'body', reportProgress?: boolean): Observable<GetPersonalInvoiceDetails>;
    public getPersonalPayoutInvoiceDetailsRoute(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<GetPersonalInvoiceDetails>>;
    public getPersonalPayoutInvoiceDetailsRoute(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<GetPersonalInvoiceDetails>>;
    public getPersonalPayoutInvoiceDetailsRoute(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<GetPersonalInvoiceDetails>(`${this.basePath}/api/accounts/settings/invoice-details/personal`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get all supported countries
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getSupportedCountriesRoute(observe?: 'body', reportProgress?: boolean): Observable<Array<Country>>;
    public getSupportedCountriesRoute(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Country>>>;
    public getSupportedCountriesRoute(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Country>>>;
    public getSupportedCountriesRoute(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<Array<Country>>(`${this.basePath}/api/accounts/settings/countries`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * List accounts
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public listAccountsRoute(observe?: 'body', reportProgress?: boolean): Observable<Array<Account>>;
    public listAccountsRoute(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Account>>>;
    public listAccountsRoute(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Account>>>;
    public listAccountsRoute(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<Array<Account>>(`${this.basePath}/api/accounts`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Request new msisdn verification
     * 
     * @param body Create new msisdn verification
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public newMsisdnVerificationRoute(body: CreateMsisdnVerificationRequest, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public newMsisdnVerificationRoute(body: CreateMsisdnVerificationRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public newMsisdnVerificationRoute(body: CreateMsisdnVerificationRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public newMsisdnVerificationRoute(body: CreateMsisdnVerificationRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling newMsisdnVerificationRoute.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<any>(`${this.basePath}/api/accounts/settings/msisdn-verification/create`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Patch mobile pin with protected views
     * 
     * @param body PatchMobileViewsPermissions
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public patchMobileViewsPermissionsRoute(body: PatchMobileViewsPermissions, observe?: 'body', reportProgress?: boolean): Observable<Account>;
    public patchMobileViewsPermissionsRoute(body: PatchMobileViewsPermissions, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Account>>;
    public patchMobileViewsPermissionsRoute(body: PatchMobileViewsPermissions, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Account>>;
    public patchMobileViewsPermissionsRoute(body: PatchMobileViewsPermissions, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling patchMobileViewsPermissionsRoute.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.patch<Account>(`${this.basePath}/api/accounts/mobile-permissions`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Partial update account
     * 
     * @param accountId Account ID
     * @param body Account to update
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public patchUpdateAccountRoute(accountId: string, body: PatchAccount, observe?: 'body', reportProgress?: boolean): Observable<Account>;
    public patchUpdateAccountRoute(accountId: string, body: PatchAccount, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Account>>;
    public patchUpdateAccountRoute(accountId: string, body: PatchAccount, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Account>>;
    public patchUpdateAccountRoute(accountId: string, body: PatchAccount, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (accountId === null || accountId === undefined) {
            throw new Error('Required parameter accountId was null or undefined when calling patchUpdateAccountRoute.');
        }
        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling patchUpdateAccountRoute.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.patch<Account>(`${this.basePath}/api/accounts/${encodeURIComponent(String(accountId))}`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Confirm email
     * 
     * @param token Confirmation token
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public postAccountVerifyEmailRoute(token: string, observe?: 'body', reportProgress?: boolean): Observable<GetSessionWithAccount>;
    public postAccountVerifyEmailRoute(token: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<GetSessionWithAccount>>;
    public postAccountVerifyEmailRoute(token: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<GetSessionWithAccount>>;
    public postAccountVerifyEmailRoute(token: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (token === null || token === undefined) {
            throw new Error('Required parameter token was null or undefined when calling postAccountVerifyEmailRoute.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.post<GetSessionWithAccount>(`${this.basePath}/api/accounts/confirm/email/${encodeURIComponent(String(token))}`,
            null,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Post call invoice details
     * 
     * @param body Create company info
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public postCallInvoiceDetailsRoute(body: PostCallInvoiceDetails, observe?: 'body', reportProgress?: boolean): Observable<GetCallInvoiceDetails>;
    public postCallInvoiceDetailsRoute(body: PostCallInvoiceDetails, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<GetCallInvoiceDetails>>;
    public postCallInvoiceDetailsRoute(body: PostCallInvoiceDetails, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<GetCallInvoiceDetails>>;
    public postCallInvoiceDetailsRoute(body: PostCallInvoiceDetails, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling postCallInvoiceDetailsRoute.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<GetCallInvoiceDetails>(`${this.basePath}/api/accounts/settings/invoice-details/call`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Post payout invoice details for company
     * 
     * @param body Create company info
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public postCompanyPayoutInvoiceDetailsRoute(body: PostCompanyInvoiceDetails, observe?: 'body', reportProgress?: boolean): Observable<GetCompanyInvoiceDetails>;
    public postCompanyPayoutInvoiceDetailsRoute(body: PostCompanyInvoiceDetails, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<GetCompanyInvoiceDetails>>;
    public postCompanyPayoutInvoiceDetailsRoute(body: PostCompanyInvoiceDetails, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<GetCompanyInvoiceDetails>>;
    public postCompanyPayoutInvoiceDetailsRoute(body: PostCompanyInvoiceDetails, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling postCompanyPayoutInvoiceDetailsRoute.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<GetCompanyInvoiceDetails>(`${this.basePath}/api/accounts/settings/invoice-details/company`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Confirm email
     * 
     * @param invitationToken Invitation token
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public postConfirmEmailViaInvitationRoute(invitationToken: string, observe?: 'body', reportProgress?: boolean): Observable<Account>;
    public postConfirmEmailViaInvitationRoute(invitationToken: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Account>>;
    public postConfirmEmailViaInvitationRoute(invitationToken: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Account>>;
    public postConfirmEmailViaInvitationRoute(invitationToken: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (invitationToken === null || invitationToken === undefined) {
            throw new Error('Required parameter invitationToken was null or undefined when calling postConfirmEmailViaInvitationRoute.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.post<Account>(`${this.basePath}/api/accounts/confirm/email/invitation/${encodeURIComponent(String(invitationToken))}`,
            null,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Post mobile pin with protected views
     * 
     * @param body PostMobileViewsPermissions
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public postMobilePinRoute(body: PostMobileViewsPermissions, observe?: 'body', reportProgress?: boolean): Observable<Account>;
    public postMobilePinRoute(body: PostMobileViewsPermissions, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Account>>;
    public postMobilePinRoute(body: PostMobileViewsPermissions, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Account>>;
    public postMobilePinRoute(body: PostMobileViewsPermissions, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling postMobilePinRoute.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<Account>(`${this.basePath}/api/accounts/mobile-permissions`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Post payout invoice details for person
     * 
     * @param body Create client invoice details
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public postPersonalPayoutInvoiceDetailsRoute(body: PostPersonalInvoiceDetails, observe?: 'body', reportProgress?: boolean): Observable<GetPersonalInvoiceDetails>;
    public postPersonalPayoutInvoiceDetailsRoute(body: PostPersonalInvoiceDetails, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<GetPersonalInvoiceDetails>>;
    public postPersonalPayoutInvoiceDetailsRoute(body: PostPersonalInvoiceDetails, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<GetPersonalInvoiceDetails>>;
    public postPersonalPayoutInvoiceDetailsRoute(body: PostPersonalInvoiceDetails, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling postPersonalPayoutInvoiceDetailsRoute.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<GetPersonalInvoiceDetails>(`${this.basePath}/api/accounts/settings/invoice-details/personal`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Update account
     * 
     * @param accountId Account ID
     * @param body Account to update
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public putAccountRoute(accountId: string, body: PutAccount, observe?: 'body', reportProgress?: boolean): Observable<Account>;
    public putAccountRoute(accountId: string, body: PutAccount, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Account>>;
    public putAccountRoute(accountId: string, body: PutAccount, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Account>>;
    public putAccountRoute(accountId: string, body: PutAccount, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (accountId === null || accountId === undefined) {
            throw new Error('Required parameter accountId was null or undefined when calling putAccountRoute.');
        }
        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling putAccountRoute.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.put<Account>(`${this.basePath}/api/accounts/${encodeURIComponent(String(accountId))}`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Put general settings
     * 
     * @param body General settings
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public putGeneralSettingsRoute(body: PutGeneralSettings, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public putGeneralSettingsRoute(body: PutGeneralSettings, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public putGeneralSettingsRoute(body: PutGeneralSettings, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public putGeneralSettingsRoute(body: PutGeneralSettings, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling putGeneralSettingsRoute.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.put<any>(`${this.basePath}/api/accounts/settings/general`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Send SMS with code for password change
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public sendPasswordChangeSmsRoute(observe?: 'body', reportProgress?: boolean): Observable<any>;
    public sendPasswordChangeSmsRoute(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public sendPasswordChangeSmsRoute(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public sendPasswordChangeSmsRoute(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.post<any>(`${this.basePath}/api/accounts/settings/mobile/change-password/sms`,
            null,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Validate mobile pin
     * 
     * @param pin mobile pin
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public validateMobilePinRoute(pin: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public validateMobilePinRoute(pin: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public validateMobilePinRoute(pin: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public validateMobilePinRoute(pin: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (pin === null || pin === undefined) {
            throw new Error('Required parameter pin was null or undefined when calling validateMobilePinRoute.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<any>(`${this.basePath}/api/accounts/mobile-permissions/${encodeURIComponent(String(pin))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
