/**
 * AnyMind API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.21
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { AdminPanelLogin } from '../model/adminPanelLogin';
import { AdminPanelSession } from '../model/adminPanelSession';
import { GetActivities } from '../model/getActivities';
import { GetAdminPanelAccount } from '../model/getAdminPanelAccount';
import { GetCallDetails } from '../model/getCallDetails';
import { GetClientActivity } from '../model/getClientActivity';
import { GetClientComplaint } from '../model/getClientComplaint';
import { GetCounters } from '../model/getCounters';
import { GetExpertComplaint } from '../model/getExpertComplaint';
import { GetPayout } from '../model/getPayout';
import { GetPotentialClient } from '../model/getPotentialClient';
import { GetProfile } from '../model/getProfile';
import { GetProfileBalance } from '../model/getProfileBalance';
import { GetProfileWithPayoutDetails } from '../model/getProfileWithPayoutDetails';
import { GetPromoCode } from '../model/getPromoCode';
import { GetTechnicalProblem } from '../model/getTechnicalProblem';
import { GetUsedPromoCode } from '../model/getUsedPromoCode';
import { PostAdminPanelAccount } from '../model/postAdminPanelAccount';
import { PostPayout } from '../model/postPayout';
import { PostPotentialClient } from '../model/postPotentialClient';
import { PostPromoCodes } from '../model/postPromoCodes';
import { PutPassword } from '../model/putPassword';
import { PutRole } from '../model/putRole';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class AdminpanelService {

    protected basePath = 'https://localhost';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (let consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Delete user&#39;s account
     * 
     * @param accountId Account ID
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteAccountRoute(accountId: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public deleteAccountRoute(accountId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public deleteAccountRoute(accountId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public deleteAccountRoute(accountId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (accountId === null || accountId === undefined) {
            throw new Error('Required parameter accountId was null or undefined when calling deleteAccountRoute.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.delete<any>(`${this.basePath}/api/adminpanel/am-accounts/${encodeURIComponent(String(accountId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get lists of account activities
     * 
     * @param accountId UUID
     * @param limit Int
     * @param offset Int
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAccountActivitiesRoute(accountId: string, limit: string, offset: string, observe?: 'body', reportProgress?: boolean): Observable<GetActivities>;
    public getAccountActivitiesRoute(accountId: string, limit: string, offset: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<GetActivities>>;
    public getAccountActivitiesRoute(accountId: string, limit: string, offset: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<GetActivities>>;
    public getAccountActivitiesRoute(accountId: string, limit: string, offset: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (accountId === null || accountId === undefined) {
            throw new Error('Required parameter accountId was null or undefined when calling getAccountActivitiesRoute.');
        }
        if (limit === null || limit === undefined) {
            throw new Error('Required parameter limit was null or undefined when calling getAccountActivitiesRoute.');
        }
        if (offset === null || offset === undefined) {
            throw new Error('Required parameter offset was null or undefined when calling getAccountActivitiesRoute.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (accountId !== undefined) {
            queryParameters = queryParameters.set('accountId', <any>accountId);
        }
        if (limit !== undefined) {
            queryParameters = queryParameters.set('limit', <any>limit);
        }
        if (offset !== undefined) {
            queryParameters = queryParameters.set('offset', <any>offset);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<GetActivities>(`${this.basePath}/api/adminpanel/account-activities`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * List all adminpanel accounts
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAccountsRoute(observe?: 'body', reportProgress?: boolean): Observable<GetAdminPanelAccount>;
    public getAccountsRoute(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<GetAdminPanelAccount>>;
    public getAccountsRoute(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<GetAdminPanelAccount>>;
    public getAccountsRoute(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<GetAdminPanelAccount>(`${this.basePath}/api/adminpanel/accounts`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get complaints rejected by experts
     * 
     * @param limit Int
     * @param offset Int
     * @param status ClientComplaintStatus
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAdminClientComplaintsRoute(limit: string, offset: string, status?: string, observe?: 'body', reportProgress?: boolean): Observable<Array<GetClientComplaint>>;
    public getAdminClientComplaintsRoute(limit: string, offset: string, status?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<GetClientComplaint>>>;
    public getAdminClientComplaintsRoute(limit: string, offset: string, status?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<GetClientComplaint>>>;
    public getAdminClientComplaintsRoute(limit: string, offset: string, status?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (limit === null || limit === undefined) {
            throw new Error('Required parameter limit was null or undefined when calling getAdminClientComplaintsRoute.');
        }
        if (offset === null || offset === undefined) {
            throw new Error('Required parameter offset was null or undefined when calling getAdminClientComplaintsRoute.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (limit !== undefined) {
            queryParameters = queryParameters.set('limit', <any>limit);
        }
        if (offset !== undefined) {
            queryParameters = queryParameters.set('offset', <any>offset);
        }
        if (status !== undefined) {
            queryParameters = queryParameters.set('status', <any>status);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<Array<GetClientComplaint>>(`${this.basePath}/api/adminpanel/client-complaints`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get list of client activities
     * 
     * @param limit Int
     * @param offset Int
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getClientActivitiesRoute(limit: string, offset: string, observe?: 'body', reportProgress?: boolean): Observable<Array<GetClientActivity>>;
    public getClientActivitiesRoute(limit: string, offset: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<GetClientActivity>>>;
    public getClientActivitiesRoute(limit: string, offset: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<GetClientActivity>>>;
    public getClientActivitiesRoute(limit: string, offset: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (limit === null || limit === undefined) {
            throw new Error('Required parameter limit was null or undefined when calling getClientActivitiesRoute.');
        }
        if (offset === null || offset === undefined) {
            throw new Error('Required parameter offset was null or undefined when calling getClientActivitiesRoute.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (limit !== undefined) {
            queryParameters = queryParameters.set('limit', <any>limit);
        }
        if (offset !== undefined) {
            queryParameters = queryParameters.set('offset', <any>offset);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<Array<GetClientActivity>>(`${this.basePath}/api/adminpanel/client-activities`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get counters
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getCountersRoute(observe?: 'body', reportProgress?: boolean): Observable<GetCounters>;
    public getCountersRoute(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<GetCounters>>;
    public getCountersRoute(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<GetCounters>>;
    public getCountersRoute(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<GetCounters>(`${this.basePath}/api/adminpanel/counters`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get adminpanel session
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getCurrentSessionRoute(observe?: 'body', reportProgress?: boolean): Observable<AdminPanelSession>;
    public getCurrentSessionRoute(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<AdminPanelSession>>;
    public getCurrentSessionRoute(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<AdminPanelSession>>;
    public getCurrentSessionRoute(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<AdminPanelSession>(`${this.basePath}/api/adminpanel/session`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get list of expert complaints
     * 
     * @param limit Int
     * @param offset Int
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getExpertComplaintsRoute(limit: string, offset: string, observe?: 'body', reportProgress?: boolean): Observable<Array<GetExpertComplaint>>;
    public getExpertComplaintsRoute(limit: string, offset: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<GetExpertComplaint>>>;
    public getExpertComplaintsRoute(limit: string, offset: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<GetExpertComplaint>>>;
    public getExpertComplaintsRoute(limit: string, offset: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (limit === null || limit === undefined) {
            throw new Error('Required parameter limit was null or undefined when calling getExpertComplaintsRoute.');
        }
        if (offset === null || offset === undefined) {
            throw new Error('Required parameter offset was null or undefined when calling getExpertComplaintsRoute.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (limit !== undefined) {
            queryParameters = queryParameters.set('limit', <any>limit);
        }
        if (offset !== undefined) {
            queryParameters = queryParameters.set('offset', <any>offset);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<Array<GetExpertComplaint>>(`${this.basePath}/api/adminpanel/expert-complaints`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get potential clients
     * 
     * @param limit Int
     * @param offset Int
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getPotentialClientsRoute(limit: string, offset: string, observe?: 'body', reportProgress?: boolean): Observable<Array<GetPotentialClient>>;
    public getPotentialClientsRoute(limit: string, offset: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<GetPotentialClient>>>;
    public getPotentialClientsRoute(limit: string, offset: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<GetPotentialClient>>>;
    public getPotentialClientsRoute(limit: string, offset: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (limit === null || limit === undefined) {
            throw new Error('Required parameter limit was null or undefined when calling getPotentialClientsRoute.');
        }
        if (offset === null || offset === undefined) {
            throw new Error('Required parameter offset was null or undefined when calling getPotentialClientsRoute.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (limit !== undefined) {
            queryParameters = queryParameters.set('limit', <any>limit);
        }
        if (offset !== undefined) {
            queryParameters = queryParameters.set('offset', <any>offset);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<Array<GetPotentialClient>>(`${this.basePath}/api/adminpanel/potential-clients`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get profile balance
     * 
     * @param profileId Profile ID
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getProfileBalanceRoute(profileId: string, observe?: 'body', reportProgress?: boolean): Observable<GetProfileBalance>;
    public getProfileBalanceRoute(profileId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<GetProfileBalance>>;
    public getProfileBalanceRoute(profileId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<GetProfileBalance>>;
    public getProfileBalanceRoute(profileId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (profileId === null || profileId === undefined) {
            throw new Error('Required parameter profileId was null or undefined when calling getProfileBalanceRoute.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<GetProfileBalance>(`${this.basePath}/api/adminpanel/profiles/${encodeURIComponent(String(profileId))}/balance`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get list of profiles
     * 
     * @param limit Int
     * @param offset Int
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getProfilesRoute(limit: string, offset: string, observe?: 'body', reportProgress?: boolean): Observable<Array<GetProfile>>;
    public getProfilesRoute(limit: string, offset: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<GetProfile>>>;
    public getProfilesRoute(limit: string, offset: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<GetProfile>>>;
    public getProfilesRoute(limit: string, offset: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (limit === null || limit === undefined) {
            throw new Error('Required parameter limit was null or undefined when calling getProfilesRoute.');
        }
        if (offset === null || offset === undefined) {
            throw new Error('Required parameter offset was null or undefined when calling getProfilesRoute.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (limit !== undefined) {
            queryParameters = queryParameters.set('limit', <any>limit);
        }
        if (offset !== undefined) {
            queryParameters = queryParameters.set('offset', <any>offset);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<Array<GetProfile>>(`${this.basePath}/api/adminpanel/profiles`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get list of profiles ready for payout
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getProfilesWithPayoutDetailsRoute(observe?: 'body', reportProgress?: boolean): Observable<Array<GetProfileWithPayoutDetails>>;
    public getProfilesWithPayoutDetailsRoute(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<GetProfileWithPayoutDetails>>>;
    public getProfilesWithPayoutDetailsRoute(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<GetProfileWithPayoutDetails>>>;
    public getProfilesWithPayoutDetailsRoute(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<Array<GetProfileWithPayoutDetails>>(`${this.basePath}/api/adminpanel/profiles/payout`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get promo codes
     * 
     * @param limit Int
     * @param offset Int
     * @param dateFrom Instant
     * @param dateTo Instant
     * @param issuer string
     * @param status PromoCodeStatus
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getPromoCodesRoute(limit: string, offset: string, dateFrom?: string, dateTo?: string, issuer?: string, status?: string, observe?: 'body', reportProgress?: boolean): Observable<Array<GetPromoCode>>;
    public getPromoCodesRoute(limit: string, offset: string, dateFrom?: string, dateTo?: string, issuer?: string, status?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<GetPromoCode>>>;
    public getPromoCodesRoute(limit: string, offset: string, dateFrom?: string, dateTo?: string, issuer?: string, status?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<GetPromoCode>>>;
    public getPromoCodesRoute(limit: string, offset: string, dateFrom?: string, dateTo?: string, issuer?: string, status?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (limit === null || limit === undefined) {
            throw new Error('Required parameter limit was null or undefined when calling getPromoCodesRoute.');
        }
        if (offset === null || offset === undefined) {
            throw new Error('Required parameter offset was null or undefined when calling getPromoCodesRoute.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (limit !== undefined) {
            queryParameters = queryParameters.set('limit', <any>limit);
        }
        if (offset !== undefined) {
            queryParameters = queryParameters.set('offset', <any>offset);
        }
        if (dateFrom !== undefined) {
            queryParameters = queryParameters.set('dateFrom', <any>dateFrom);
        }
        if (dateTo !== undefined) {
            queryParameters = queryParameters.set('dateTo', <any>dateTo);
        }
        if (issuer !== undefined) {
            queryParameters = queryParameters.set('issuer', <any>issuer);
        }
        if (status !== undefined) {
            queryParameters = queryParameters.set('status', <any>status);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<Array<GetPromoCode>>(`${this.basePath}/api/adminpanel/promo-codes`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get list of technical issues
     * 
     * @param limit Int
     * @param offset Int
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getTechnicalIssuesRoute(limit: string, offset: string, observe?: 'body', reportProgress?: boolean): Observable<Array<GetTechnicalProblem>>;
    public getTechnicalIssuesRoute(limit: string, offset: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<GetTechnicalProblem>>>;
    public getTechnicalIssuesRoute(limit: string, offset: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<GetTechnicalProblem>>>;
    public getTechnicalIssuesRoute(limit: string, offset: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (limit === null || limit === undefined) {
            throw new Error('Required parameter limit was null or undefined when calling getTechnicalIssuesRoute.');
        }
        if (offset === null || offset === undefined) {
            throw new Error('Required parameter offset was null or undefined when calling getTechnicalIssuesRoute.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (limit !== undefined) {
            queryParameters = queryParameters.set('limit', <any>limit);
        }
        if (offset !== undefined) {
            queryParameters = queryParameters.set('offset', <any>offset);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<Array<GetTechnicalProblem>>(`${this.basePath}/api/adminpanel/technical-issues`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get used promo codes
     * 
     * @param limit Int
     * @param offset Int
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getUsedPromoCodesRoute(limit: string, offset: string, observe?: 'body', reportProgress?: boolean): Observable<Array<GetUsedPromoCode>>;
    public getUsedPromoCodesRoute(limit: string, offset: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<GetUsedPromoCode>>>;
    public getUsedPromoCodesRoute(limit: string, offset: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<GetUsedPromoCode>>>;
    public getUsedPromoCodesRoute(limit: string, offset: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (limit === null || limit === undefined) {
            throw new Error('Required parameter limit was null or undefined when calling getUsedPromoCodesRoute.');
        }
        if (offset === null || offset === undefined) {
            throw new Error('Required parameter offset was null or undefined when calling getUsedPromoCodesRoute.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (limit !== undefined) {
            queryParameters = queryParameters.set('limit', <any>limit);
        }
        if (offset !== undefined) {
            queryParameters = queryParameters.set('offset', <any>offset);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<Array<GetUsedPromoCode>>(`${this.basePath}/api/adminpanel/promo-codes/used`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Logout from current adminpanel session
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public logoutCurrentSessionRoute(observe?: 'body', reportProgress?: boolean): Observable<any>;
    public logoutCurrentSessionRoute(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public logoutCurrentSessionRoute(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public logoutCurrentSessionRoute(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.delete<any>(`${this.basePath}/api/adminpanel/session`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Accept comment report
     * 
     * @param commentId commentId
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public postAcceptCommentReportRoute(commentId: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public postAcceptCommentReportRoute(commentId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public postAcceptCommentReportRoute(commentId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public postAcceptCommentReportRoute(commentId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (commentId === null || commentId === undefined) {
            throw new Error('Required parameter commentId was null or undefined when calling postAcceptCommentReportRoute.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.post<any>(`${this.basePath}/api/adminpanel/comments-report/${encodeURIComponent(String(commentId))}/accept`,
            null,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Block account
     * 
     * @param accountId Account ID
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public postAccountBlockRoute(accountId: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public postAccountBlockRoute(accountId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public postAccountBlockRoute(accountId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public postAccountBlockRoute(accountId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (accountId === null || accountId === undefined) {
            throw new Error('Required parameter accountId was null or undefined when calling postAccountBlockRoute.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.post<any>(`${this.basePath}/api/adminpanel/am-accounts/${encodeURIComponent(String(accountId))}/block`,
            null,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Add adminpanel account
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public postAccountRoute(body: PostAdminPanelAccount, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public postAccountRoute(body: PostAdminPanelAccount, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public postAccountRoute(body: PostAdminPanelAccount, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public postAccountRoute(body: PostAdminPanelAccount, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling postAccountRoute.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<any>(`${this.basePath}/api/adminpanel/accounts`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Unblock account
     * 
     * @param accountId Account ID
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public postAccountUnblockRoute(accountId: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public postAccountUnblockRoute(accountId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public postAccountUnblockRoute(accountId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public postAccountUnblockRoute(accountId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (accountId === null || accountId === undefined) {
            throw new Error('Required parameter accountId was null or undefined when calling postAccountUnblockRoute.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.post<any>(`${this.basePath}/api/adminpanel/am-accounts/${encodeURIComponent(String(accountId))}/unblock`,
            null,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get call activity details
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public postActivityDetailsRoute(body: AdminPanelLogin, observe?: 'body', reportProgress?: boolean): Observable<GetCallDetails>;
    public postActivityDetailsRoute(body: AdminPanelLogin, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<GetCallDetails>>;
    public postActivityDetailsRoute(body: AdminPanelLogin, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<GetCallDetails>>;
    public postActivityDetailsRoute(body: AdminPanelLogin, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling postActivityDetailsRoute.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<GetCallDetails>(`${this.basePath}/api/adminpanel/activity-details`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Accept client complaint
     * 
     * @param sueId sueId
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public postAdminAcceptComplaintRoute(sueId: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public postAdminAcceptComplaintRoute(sueId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public postAdminAcceptComplaintRoute(sueId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public postAdminAcceptComplaintRoute(sueId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (sueId === null || sueId === undefined) {
            throw new Error('Required parameter sueId was null or undefined when calling postAdminAcceptComplaintRoute.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.post<any>(`${this.basePath}/api/adminpanel/client-complaints/${encodeURIComponent(String(sueId))}/accept`,
            null,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Reject client complaint
     * 
     * @param sueId sueId
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public postAdminRejectComplaintRoute(sueId: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public postAdminRejectComplaintRoute(sueId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public postAdminRejectComplaintRoute(sueId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public postAdminRejectComplaintRoute(sueId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (sueId === null || sueId === undefined) {
            throw new Error('Required parameter sueId was null or undefined when calling postAdminRejectComplaintRoute.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.post<any>(`${this.basePath}/api/adminpanel/client-complaints/${encodeURIComponent(String(sueId))}/reject`,
            null,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Disable creating free services
     * 
     * @param accountId Account ID
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public postDisableCreateFreeServiceRoute(accountId: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public postDisableCreateFreeServiceRoute(accountId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public postDisableCreateFreeServiceRoute(accountId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public postDisableCreateFreeServiceRoute(accountId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (accountId === null || accountId === undefined) {
            throw new Error('Required parameter accountId was null or undefined when calling postDisableCreateFreeServiceRoute.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.post<any>(`${this.basePath}/api/adminpanel/am-accounts/${encodeURIComponent(String(accountId))}/disable-free-service`,
            null,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Enable creating free services
     * 
     * @param accountId Account ID
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public postEnableCreateFreeServiceRoute(accountId: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public postEnableCreateFreeServiceRoute(accountId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public postEnableCreateFreeServiceRoute(accountId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public postEnableCreateFreeServiceRoute(accountId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (accountId === null || accountId === undefined) {
            throw new Error('Required parameter accountId was null or undefined when calling postEnableCreateFreeServiceRoute.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.post<any>(`${this.basePath}/api/adminpanel/am-accounts/${encodeURIComponent(String(accountId))}/enable-free-service`,
            null,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Login to admin panel using email and password
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public postLoginRoute(body: AdminPanelLogin, observe?: 'body', reportProgress?: boolean): Observable<AdminPanelSession>;
    public postLoginRoute(body: AdminPanelLogin, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<AdminPanelSession>>;
    public postLoginRoute(body: AdminPanelLogin, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<AdminPanelSession>>;
    public postLoginRoute(body: AdminPanelLogin, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling postLoginRoute.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<AdminPanelSession>(`${this.basePath}/api/adminpanel/session`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Generate payout for given profile
     * 
     * @param profileId ProfileId
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public postPayoutRoute(profileId: string, body: PostPayout, observe?: 'body', reportProgress?: boolean): Observable<GetPayout>;
    public postPayoutRoute(profileId: string, body: PostPayout, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<GetPayout>>;
    public postPayoutRoute(profileId: string, body: PostPayout, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<GetPayout>>;
    public postPayoutRoute(profileId: string, body: PostPayout, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (profileId === null || profileId === undefined) {
            throw new Error('Required parameter profileId was null or undefined when calling postPayoutRoute.');
        }
        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling postPayoutRoute.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<GetPayout>(`${this.basePath}/api/adminpanel/profiles/${encodeURIComponent(String(profileId))}/payout`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Create potential client
     * 
     * @param body body
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public postPotentialClientRoute(body: PostPotentialClient, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public postPotentialClientRoute(body: PostPotentialClient, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public postPotentialClientRoute(body: PostPotentialClient, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public postPotentialClientRoute(body: PostPotentialClient, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling postPotentialClientRoute.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<any>(`${this.basePath}/api/adminpanel/potential-clients`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Create promo codes
     * 
     * @param body body
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public postPromoCodeRoute(body: PostPromoCodes, observe?: 'body', reportProgress?: boolean): Observable<Array<GetPromoCode>>;
    public postPromoCodeRoute(body: PostPromoCodes, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<GetPromoCode>>>;
    public postPromoCodeRoute(body: PostPromoCodes, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<GetPromoCode>>>;
    public postPromoCodeRoute(body: PostPromoCodes, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling postPromoCodeRoute.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<Array<GetPromoCode>>(`${this.basePath}/api/adminpanel/promo-codes`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Reject comment report
     * 
     * @param commentId commentId
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public postRejectCommentReportRoute(commentId: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public postRejectCommentReportRoute(commentId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public postRejectCommentReportRoute(commentId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public postRejectCommentReportRoute(commentId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (commentId === null || commentId === undefined) {
            throw new Error('Required parameter commentId was null or undefined when calling postRejectCommentReportRoute.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.post<any>(`${this.basePath}/api/adminpanel/comments-report/${encodeURIComponent(String(commentId))}/reject`,
            null,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Update account&#39;s password
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public putPasswordRoute(body: PutPassword, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public putPasswordRoute(body: PutPassword, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public putPasswordRoute(body: PutPassword, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public putPasswordRoute(body: PutPassword, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling putPasswordRoute.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.put<any>(`${this.basePath}/api/adminpanel/accounts/password`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Update account&#39;s role
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public putRoleRoute(body: PutRole, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public putRoleRoute(body: PutRole, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public putRoleRoute(body: PutRole, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public putRoleRoute(body: PutRole, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling putRoleRoute.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.put<any>(`${this.basePath}/api/adminpanel/accounts/role`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
