export * from './account.service';
import { AccountService } from './account.service';
export * from './activities.service';
import { ActivitiesService } from './activities.service';
export * from './adminpanel.service';
import { AdminpanelService } from './adminpanel.service';
export * from './employment.service';
import { EmploymentService } from './employment.service';
export * from './files.service';
import { FilesService } from './files.service';
export * from './finances.service';
import { FinancesService } from './finances.service';
export * from './invitation.service';
import { InvitationService } from './invitation.service';
export * from './payments.service';
import { PaymentsService } from './payments.service';
export * from './payouts.service';
import { PayoutsService } from './payouts.service';
export * from './presence.service';
import { PresenceService } from './presence.service';
export * from './profile.service';
import { ProfileService } from './profile.service';
export * from './promoCodes.service';
import { PromoCodesService } from './promoCodes.service';
export * from './ratel.service';
import { RatelService } from './ratel.service';
export * from './recoverPassword.service';
import { RecoverPasswordService } from './recoverPassword.service';
export * from './registration.service';
import { RegistrationService } from './registration.service';
export * from './search.service';
import { SearchService } from './search.service';
export * from './service.service';
import { ServiceService } from './service.service';
export * from './serviceUsageEvent.service';
import { ServiceUsageEventService } from './serviceUsageEvent.service';
export * from './session.service';
import { SessionService } from './session.service';
export * from './version.service';
import { VersionService } from './version.service';
export * from './views.service';
import { ViewsService } from './views.service';
export * from './widget.service';
import { WidgetService } from './widget.service';
export * from './wizard.service';
import { WizardService } from './wizard.service';
export * from './ws.service';
import { WsService } from './ws.service';
export const APIS = [AccountService, ActivitiesService, AdminpanelService, EmploymentService, FilesService, FinancesService, InvitationService, PaymentsService, PayoutsService, PresenceService, ProfileService, PromoCodesService, RatelService, RecoverPasswordService, RegistrationService, SearchService, ServiceService, ServiceUsageEventService, SessionService, VersionService, ViewsService, WidgetService, WizardService, WsService];
